# Intern Performance Dataset Creation

In [5]:
import pandas as pd
import numpy as np

In [6]:
np.random.seed(42)

data = {
    "Intern_ID": range(1, 101),
    "Department": np.random.choice(["IT", "HR", "Marketing", "Finance"], 100),
    "Tasks_Assigned": np.random.randint(5, 20, 100),
    "Tasks_Completed": np.random.randint(3, 20, 100),
    "Hours_Worked": np.random.randint(80, 200, 100),
    "Attendance": np.random.randint(70, 100, 100),
    "Performance_Score": np.random.randint(50, 100, 100)
}

df = pd.DataFrame(data)

In [7]:
df["Completion_Rate"] = (df["Tasks_Completed"] / df["Tasks_Assigned"]) * 100

In [8]:
df.head()

,Intern_ID,Department,Tasks_Assigned,Tasks_Completed,Hours_Worked,Attendance,Performance_Score,Completion_Rate
0,1,Marketing,19,6,183,93,72,31.578947
1,2,Finance,6,7,163,87,58,116.666667
2,3,IT,14,9,178,84,61,64.285714
3,4,Marketing,16,15,191,91,50,93.750000
4,5,Marketing,6,17,168,92,50,283.333333

In [9]:
df.shape

(100, 8)

In [10]:
df.to_csv("../dataset/intern_data.csv", index=False)

In [ ]:
df = pd.read_csv("../dataset/intern_data.csv")
df.head()

,Intern_ID,Department,Tasks_Assigned,Tasks_Completed,Hours_Worked,Attendance,Performance_Score,Completion_Rate
0,1,Marketing,19,6,183,93,72,31.578947
1,2,Finance,6,7,163,87,58,116.666667
2,3,IT,14,9,178,84,61,64.285714
3,4,Marketing,16,15,191,91,50,93.750000
4,5,Marketing,6,17,168,92,50,283.333333

In [12]:
df.isnull().sum()

Intern_ID            0
Department           0
Tasks_Assigned       0
Tasks_Completed      0
Hours_Worked         0
Attendance           0
Performance_Score    0
Completion_Rate      0
dtype: int64

In [13]:
df.dtypes

Intern_ID              int64
Department               str
Tasks_Assigned         int64
Tasks_Completed        int64
Hours_Worked           int64
Attendance             int64
Performance_Score      int64
Completion_Rate      float64
dtype: object

In [14]:
df.drop_duplicates(inplace=True)

In [15]:
df["Completion_Rate"] = df["Completion_Rate"].clip(0, 100)

In [16]:
df.describe()

,Intern_ID,Tasks_Assigned,Tasks_Completed,Hours_Worked,Attendance,Performance_Score,Completion_Rate
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,12.670000,10.240000,141.390000,85.760000,74.020000,70.924600
std,29.011492,4.410857,5.220627,34.102607,8.601292,14.424992,29.415962
min,1.000000,5.000000,3.000000,83.000000,70.000000,50.000000,18.750000
25%,25.750000,9.000000,6.000000,111.750000,79.000000,61.000000,44.270833
50%,50.500000,13.000000,9.000000,139.500000,87.000000,75.000000,75.735294
75%,75.250000,16.000000,14.000000,174.500000,93.000000,84.250000,100.000000
max,100.000000,19.000000,19.000000,199.000000,99.000000,99.000000,100.000000

In [17]:
df.to_csv("../dataset/intern_data_cleaned.csv", index=False)